### ISSUE TITLE
Compilations problem

### ISSUE THREAD

**Issue by BrunoDutertre** [makaimann/smt-switch#3]
CVC4 does not install cleanly on MacOS X so ./contrib/setup-cvc4.sh fails.
The bug is in CVC4's contrib/get-antlr-3.4. It use realpath, but
there's no realpath on the Mac.

After fixing the previous problem, I got a compilation error for sort.cpp:

./src/sort.cpp:12:55: error: implicit instantiation of undefined template 'std::__1::array<std::__1::basic_string_view<char, std::__1::char_traits<char> >, 6>'
constexpr std::array<std::string_view, NUM_SORT_CONS> generate_sortcon2str()

You need to add
```
include <array>
```
at the beginning of sort.cpp. That fixes the problem.

**Comment by makaimann** [comment]
Thanks @BrunoDutertre!

I fixed the include issue with this commit: 984c1ab6ca575228be5bcd62528132650d2b2182

Quick question, when you fixed the `get-antlr-3.4` script did you use `grealpath` on Mac or something else?

**Comment by makaimann** [comment]
Actually, nevermind. I just used an alternative implementation.

**Comment by BrunoDutertre** [comment]
My fix didn't use grealpath. I stored the top directory in a shell variable then
use it to compute PREFIX:

```
source "$(dirname "$0")/get-script-header.sh"
CURRENT_DIR=`pwd`
ANTLR_HOME_DIR=antlr-3.4
...
...
# Use an absolute path for the installation directory to avoid spurious libtool
# warnings about the ANTLR library having moved
+PREFIX=$CURRENT_DIR/$ANTLR_HOME_DIR
 ```

**Comment by makaimann** [comment]
Great, thanks! This is resolved since https://github.com/CVC4/CVC4/pull/3117 has been merged.
