### ISSUE TITLE
Compilation problem 2

### ISSUE THREAD

**Issue by BrunoDutertre** [makaimann/smt-switch#4]
In contrib/setup-cvc4.sh, cvc4 is configured using
```
CXXFLAGS=-fPIC CFLAGS=-fPIC ./configure.sh --static
```
but cvc4 does not build in mode  --static on MacOS X.
This seems to work:
```
CXXFLAGS=-fPIC CFLAGS=-fPIC ./configure.sh --static --no-static-binary
```

**Comment by makaimann** [comment]
Thanks @BrunoDutertre, fixed with 27a1d21acfe0cd827fc6edf4d3e7a1a179c7c34d.
